extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
  filelog:
    include: [ path to your log file *.log ]
    start_at: beginning

  opencensus:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

processors:
  resourcedetection:
    detectors: [system]
    system:
      hostname_sources: ["os"]
  batch:

exporters:
  logging:
    verbosity: detailed
  otlp:
    endpoint: "ingress.coralogix.us:443"
    headers:
      "Authorization": "7d6c036d-1bbb-7430-7827-cccfc339dcce"
      "CX-Application-Name": "exp-test"
      "CX-Subsystem-Name": "exp-test"
      ApplicationName: "exp-test"
      ApiName: "exp-test"

service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [otlp]

    metrics:
      receivers: [otlp, hostmetrics, opencensus, prometheus]
      processors: [resourcedetection, batch]
      exporters: [otlp]

    logs:
      receivers: [otlp,filelog]
      processors: [resourcedetection,batch]
      exporters: [otlp]

  extensions: [health_check, pprof, zpages]