site_name: Workshops
site_url: http://coralogix.github.io
site_author: Coralogix Solution Architects
site_description: Coralogix workshops for observability and integrations
repo_url: http://github.com/coralogix/workshops
copyright: Copyright Coralogix. All rights reserved.

theme:
  name: material
  # custom_dir: overrides
  palette:
    primary: green
  logo: ../images/horizontal.png
  favicon: ../images/favicon.png
  font:
      text: "Nunito Sans"
      code: "Jetbrains mono"
  # include_search_page: false
  # search_index_only: true
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - toc.follow

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - OpenTelemetry APM Instrumentation:
    - .NET Windows: otel/dotnet-windows/index.md