---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-marketing-node-reqs
  namespace: default
spec:
  selector:
    matchLabels:
      name: cx-marketing-node-reqs
  template:
    metadata:
      labels:
        name: cx-marketing-node-reqs
    spec:
      containers:
      - name: cx-marketing-node-reqs
        image: public.ecr.aws/w3s4j9x9/microservices-demo:node
        imagePullPolicy: Always
        workingDir: /home/code
        env:
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: cx-marketing-node-reqs
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: application.name=cx-marketing-node-reqs,api.name=cx-marketing-node-reqs,cx.application.name=cx-marketing-node-reqs,cx.subsystem.name=cx-marketing-node-reqs
        # - name: OTEL_NODE_RESOURCE_DETECTORS
        #   value: env,host,os
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        # - name: NODE_OPTIONS
        #   value: "--require @opentelemetry/auto-instrumentations-node/register"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_IP):4317
        - name: NODE_TEST_HOST
          value: "http://cx-payment-gateway-flask"
        - name: NODE_TEST_PORT 
          value: "5000"
        # command: ["/bin/sh"]
        # args: ["run-client.sh"]
        # test if needed
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]